carteira:
  tickers:
    - ABEV3
    - ALOS3
    - ANIM3
    - ASAI3
    - AURE3
    - AZZA3
    - BBAS3
    - BBSE3
    - BBDC3
    - BBDC4
    - BPAC11
    - BRAP4
    - BRAV3
    - BRKM5
    - B3SA3
    - CEAB3
    - CMIG4
    - CMIM3
    - COGN3
    - CPLE3
    - CPLE6
    - CPFE3
    - CSAN3
    - CSMG3
    - CURY3
    - CVCB3
    - CYRE3
    - DIRE3
    - ECOR3
    - ELET3
    - ELET6
    - EMBR3
    - ENGI11
    - ENEV3
    - EGIE3
    - EQTL3
    - EZTC3
    - FLRY3
    - GGBR4
    - GOAU4
    - GGPS3
    - GMAT3
    - HAPV3
    - HYPE3
    - IGTI11
    - INTB3
    - IRBR3
    - ISAE4
    - ITSA4
    - ITUB4
    - KLBN11
    - LREN3
    - LSWA3
    - MBRF3
    - MGLU3
    - MOTV3
    - MOVI3
    - MRVE3
    - MULT3
    - NATU3
    - PCAR3
    - PETR3
    - PETR4
    - PSSA3
    - PRIO3
    - RADL3
    - RAIZ4
    - RAPT4
    - RDOR3
    - RAIL3
    - RECV3
    - RENT3
    - SABESP3
    - SAPR11
    - SANB11
    - SBSP3
    - SMAL11
    - SMFT3
    - SMTO3
    - SRNA3
    - SUZB3
    - TAEE11
    - TEND3
    - TIMS3
    - TOTS3
    - UGPA3
    - USIM5
    - VAMO3
    - VBBR3
    - VIVA3
    - VALE3
    - WEGE3
    - YDUQ3
    - BOVA11
