portfolio:
  name: Carteira_Base
  defaults:
    provider: yahoo
    interval: "1d"
    start: "2023-01-01" # ~3 anos de histórico
    end: null
  assets:
    - name: BOVA11
      ticker: BOVA11.SA
    - name: PETR4
      ticker: PETR4.SA
    - name: VALE3
      ticker: VALE3.SA
    - name: BBAS3
      ticker: BBAS3.SA
    - name: ITSA4
      ticker: ITSA4.SA

